export const DATABASE_ID = process.env.NEXT_PUBLIC_DB_ID || '6a4c8598001da3b0d7f0';

export const COLLECTIONS = {
  users: process.env.NEXT_PUBLIC_USER_COLLECTION || 'users',
  umkmProfiles: process.env.NEXT_PUBLIC_UMKM_PROFILE_COLLECTION || 'umkm_profiles',
  creatorProfiles: process.env.NEXT_PUBLIC_CREATOR_COLLECTION || 'creator_profiles',
  creatorSocialAccounts: process.env.NEXT_PUBLIC_CREATOR_SOCIAL_ACCOUNT_COLLECTION || 'creator_social_accounts',
  creatorPortfolios: process.env.NEXT_PUBLIC_CREATOR_PORTFOLIO_COLLECTION || 'creator_portfolios',
  userStorageUsage: process.env.NEXT_PUBLIC_USER_STORAGE_USAGE_COLLECTION || 'user_storage_usage',
  userFiles: process.env.NEXT_PUBLIC_USER_FILES_COLLECTION || 'user_files',
  conversations: process.env.NEXT_PUBLIC_CONVERSATION_COLLECTION || 'conversations',
  messages: process.env.NEXT_PUBLIC_MESSAGE_COLLECTION || 'messages',
  notifications: process.env.NEXT_PUBLIC_NOTIFICATION_COLLECTION || 'notifications',
  rateCards: process.env.NEXT_PUBLIC_RATE_CARD_COLLECTION || 'rate_cards',
  rateCardPackages: process.env.NEXT_PUBLIC_RATE_CARD_PACKAGE_COLLECTION || 'rate_card_packages',
  offers: process.env.NEXT_PUBLIC_OFFER_COLLECTION || 'offers',
  orders: process.env.NEXT_PUBLIC_ORDER_COLLECTION || 'orders',
  deliverables: process.env.NEXT_PUBLIC_DELIVERABLE_COLLECTION || 'deliverables',
  revisions: process.env.NEXT_PUBLIC_REVISION_COLLECTION || 'revisions',
  wallets: process.env.NEXT_PUBLIC_WALLET_COLLECTION || 'wallets',
  payments: process.env.NEXT_PUBLIC_PAYMENT_COLLECTION || 'payments',
  transactions: process.env.NEXT_PUBLIC_TRANSACTION_COLLECTION || 'transactions',
  escrows: process.env.NEXT_PUBLIC_ESCROW_COLLECTION || 'escrows',
  withdrawals: process.env.NEXT_PUBLIC_WITHDRAWAL_COLLECTION || 'withdrawals',
  campaigns: process.env.NEXT_PUBLIC_CAMPAIGN_COLLECTION || 'campaigns',
  campaignAssets: process.env.NEXT_PUBLIC_CAMPAIGN_ASSET_COLLECTION || 'campaign_assets',
  campaignBriefs: process.env.NEXT_PUBLIC_CAMPAIGN_BRIEF_COLLECTION || 'campaign_briefs',
  claims: process.env.NEXT_PUBLIC_CLAIM_COLLECTION || 'campaign_claims',
  submissions: process.env.NEXT_PUBLIC_SUBMISSION_COLLECTION || 'campaign_submissions',
  fraudChecks: process.env.NEXT_PUBLIC_FRAUD_CHECK_COLLECTION || 'fraud_checks',
} as const;

export const FUNCTIONS = {
  createUserProfile: process.env.NEXT_PUBLIC_CREATE_USER_PROFILE_FUNCTION_ID || 'create-user-profile',
  validateAndUpload: process.env.NEXT_PUBLIC_VALIDATE_AND_UPLOAD_FUNCTION_ID || 'validate-and-upload',
  deleteFile: process.env.NEXT_PUBLIC_DELETE_FILE_FUNCTION_ID || 'delete-file',
  createPayment: process.env.NEXT_PUBLIC_CREATE_PAYMENT_FUNCTION_ID || 'create-payment',
  calculateCampaignReward: process.env.NEXT_PUBLIC_CALCULATE_REWARD_FUNCTION_ID || 'calculate-campaign-reward',
  campaignClaimed: process.env.NEXT_PUBLIC_CAMPAIGN_CLAIMED_FUNCTION_ID || 'campaign-claimed',
  expireStaleClaims: process.env.NEXT_PUBLIC_EXPIRE_CLAIMS_FUNCTION_ID || 'expire-stale-claims',
} as const;
